export const wingdingsDescriptions = [
  "Space",
  "Lower left pencil",
  "Scissors",
  "Upper blade scissors",
  "Eyeglasses",
  "Ringing bell",
  "Book",
  "Candle",
  "Touchtone telephone",
  "Telephone location sign",
  "Back of envelope",
  "Stamped envelope",
  "Closed mailbox",
  "Open mailbox",
  "File folder",
  "Open file folder",
  "Page facing up",
  "Page",
  "Pages",
  "File cabinet",
  "Hourglass",
  "Wired keyboard",
  "Two button mouse",
  "Trackball",
  "Old personal computer",
  "Hard disk",
  "Hard shell floppy disk",
  "Soft shell floppy disk",
  "Tape drive",
  "Writing hand",
  "Left writing hand",
  "Peace sign",
  "OK sign",
  "Thumbs up",
  "Thumbs down",
  "Left point",
  "Right point",
  "Point up",
  "Point down",
  "Open palm",
  "Smiling face",
  "Straight face",
  "Sad face",
  "Bomb",
  "Poison",
  "Waving flag",
  "Calm flag",
  "Airplane",
  "Bright sun",
  "Droplet",
  "Snowflake",
  "Christian cross",
  "3D Christian cross",
  "Celtic cross",
  "Maltese cross",
  "Star of David",
  "Star and crescent",
  "Yin Yang",
  "Devanagari Om",
  "Wheel of Dharma",
  "Aries",
  "Taurus",
  "Gemini",
  "Leo",
  "Virgo",
  "Libra",
];
